
steps:
  build:
    image: alpine
    commands:
      - apk add --no-cache $SCHEME make git restic
      - cd root
      - make build
      - CI=1 make test
    when:
      - event: push
        branch: [master, development]

matrix:
  SCHEME:
    - guile
