
steps:
  build:
    image: alpine
    commands:
      - apk add --no-cache $SCHEME make git guix
      - cd root
      - make build
      - CI=1 make test
    when:
      branch: [master, development]

matrix:
  SCHEME:
    - guile
