
name: Makefile CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        scheme: [guile-3.0]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.scheme }} git restic
    - name: Conditional Guix installation
      if: github.event_name == 'schedule'
      run: sudo apt-get install -y guix
    - name: Run build
      run: cd root && make build
    - name: Conditional Guix initialization
      if: github.event_name == 'schedule'
      run: guix pull --verbosity=0
    - name: Run test
      if: github.event_name != 'schedule'
      run: cd root && CI=1 make test
    - name: Conditional run test
      if: github.event_name == 'schedule'
      run: cd root && export GUIX_PROFILE="$HOME/.config/guix/current" && . "$GUIX_PROFILE/etc/profile" && CI=1 make test
