
name: Makefile CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        scheme: [guile-3.0]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.scheme }} git guix
    - name: Run build
      run: cd root && make build
    - name: Initialize guix
      run: guix pull --verbosity=0
    - name: Run test
      run: cd root && export GUIX_PROFILE="$HOME/.config/guix/current" && . "$GUIX_PROFILE/etc/profile" && CI=1 make test
